---
- name: clean if there are any files
  file:
    path: "{{ tower_install_directory }}/"
    state: absent
- name: create install directory
  file:
    path: "{{ tower_install_directory }}"
    state: directory


- name: get latest program from internet
  get_url:
    url: "{{ tower_installation_program }}"
    dest: "{{ tower_install_directory }}"
  register: tower_program_get_resilt

- name: unarchive targz file
  unarchive:
    src: "{{ tower_program_get_resilt.dest }}"
    dest: "{{ tower_install_directory }}"
    remote_src: true

# can't get name unarchived directory from unarchive module return
- name: get name of unarchived directory
  find:
    paths: "{{ tower_install_directory }}"
    file_type: directory
  register: find_result
  failed_when: find_result.matched != 1

- name:
  set_fact:
    tower_install_script_path: "{{ find_result.files[0].path }}"
